export interface Property {
  id: number
  title: string
  location: string
  price: string | number
  bedrooms: number
  bathrooms: number
  area?: string
  squareFeet?: number
  image: string
  status: "Ready" | "Off-plan" | "For Rent" | "Sold" | "For Sale"
  featured: boolean
  description: string
  features: string[]
  amenities: string[]
  videoId?: string
  images: string[]
  // Enhanced properties
  type:
    | "Villa"
    | "Apartment"
    | "Penthouse"
    | "Mansion"
    | "House"
    | "Townhouse"
    | "Studio"
    | "Cottage"
    | "Cabin"
    | "Chalet"
  yearBuilt?: number
  parkingSpaces?: number
  furnished?: boolean
  petFriendly?: boolean
  pricePerSqFt?: number
  lastUpdated?: string
  viewCount?: number
  agent?: {
    name: string
    phone: string
    email: string
    image?: string
  }
  highlights?: string[]
  nearbyPlaces?: {
    schools?: string[]
    hospitals?: string[]
    shopping?: string[]
    transport?: string[]
  }
  coordinates?: {
    lat: number
    lng: number
  }
}

export const properties: Property[] = [
  {
    id: 1,
    title: "Luxury Villa in Bali",
    description: "A stunning villa with a private pool and ocean views.",
    location: "Bali, Indonesia",
    price: 1500000,
    bedrooms: 4,
    bathrooms: 4,
    squareFeet: 3000,
    type: "Villa",
    status: "For Sale",
    image: "/properties/luxury-villa-bali.png",
    featured: true, // Marked as favorite
    features: ["Private Pool", "Ocean View", "Garden", "Modern Kitchen"],
    amenities: ["Swimming Pool", "Security", "Parking", "WiFi"],
    highlights: ["Ocean View", "Private Pool", "Luxury Finishes"],
    images: [
      "/properties/luxury-villa-bali.png",
      "/placeholder.svg?height=300&width=400&text=Villa Interior",
      "/placeholder.svg?height=300&width=400&text=Pool Area",
    ],
    yearBuilt: 2020,
    parkingSpaces: 2,
    furnished: true,
    petFriendly: true,
    pricePerSqFt: 500,
    lastUpdated: "2024-01-15",
    viewCount: 1247,
    agent: {
      name: "Sarah Johnson",
      phone: "+62 123 456 789",
      email: "sarah@vlrealestate.com",
    },
    coordinates: { lat: -8.3405, lng: 115.092 },
  },
  {
    id: 2,
    title: "Modern Apartment in New York",
    description: "A stylish apartment in the heart of Manhattan.",
    location: "New York, USA",
    price: 2500000,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    type: "Apartment",
    status: "For Sale",
    image: "/properties/modern-apartment-new-york.png",
    featured: false,
    features: ["City View", "Modern Design", "High Floor", "Balcony"],
    amenities: ["Gym", "Concierge", "Rooftop", "Security"],
    highlights: ["Manhattan Location", "City Views", "Modern Design"],
    images: [
      "/properties/modern-apartment-new-york.png",
      "/placeholder.svg?height=300&width=400&text=Living Room",
      "/placeholder.svg?height=300&width=400&text=Bedroom",
    ],
    yearBuilt: 2019,
    parkingSpaces: 1,
    furnished: false,
    petFriendly: false,
    pricePerSqFt: 2083,
    lastUpdated: "2024-01-10",
    viewCount: 892,
    agent: {
      name: "Michael Chen",
      phone: "+1 555 123 4567",
      email: "michael@vlrealestate.com",
    },
    coordinates: { lat: 40.7589, lng: -73.9851 },
  },
  {
    id: 3,
    title: "Charming Cottage in the Cotswolds",
    description: "A cozy cottage surrounded by beautiful countryside.",
    location: "Cotswolds, UK",
    price: 800000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1800,
    type: "Cottage",
    status: "For Sale",
    image: "/properties/charming-cottage-cotswolds.png",
    featured: false,
    features: ["Garden", "Fireplace", "Original Features", "Countryside Views"],
    amenities: ["Garden", "Parking", "Storage", "Heating"],
    highlights: ["Countryside Location", "Original Features", "Large Garden"],
    images: [
      "/properties/charming-cottage-cotswolds.png",
      "/placeholder.svg?height=300&width=400&text=Garden View",
      "/placeholder.svg?height=300&width=400&text=Interior",
    ],
    yearBuilt: 1850,
    parkingSpaces: 2,
    furnished: false,
    petFriendly: true,
    pricePerSqFt: 444,
    lastUpdated: "2024-01-08",
    viewCount: 654,
    agent: {
      name: "Emma Thompson",
      phone: "+44 20 7123 4567",
      email: "emma@vlrealestate.com",
    },
    coordinates: { lat: 51.833, lng: -1.8433 },
  },
  {
    id: 4,
    title: "Beachfront House in Malibu",
    description: "A luxurious house with direct access to the beach.",
    location: "Malibu, USA",
    price: 5000000,
    bedrooms: 5,
    bathrooms: 5,
    squareFeet: 4000,
    type: "House",
    status: "For Sale",
    image: "/properties/beachfront-house-malibu.png",
    featured: true, // Marked as favorite
    features: ["Beach Access", "Ocean View", "Large Deck", "Modern Kitchen"],
    amenities: ["Beach Access", "Pool", "Garage", "Security"],
    highlights: ["Beachfront Location", "Ocean Views", "Luxury Finishes"],
    images: [
      "/properties/beachfront-house-malibu.png",
      "/placeholder.svg?height=300&width=400&text=Beach View",
      "/placeholder.svg?height=300&width=400&text=Deck Area",
    ],
    yearBuilt: 2018,
    parkingSpaces: 3,
    furnished: true,
    petFriendly: true,
    pricePerSqFt: 1250,
    lastUpdated: "2024-01-12",
    viewCount: 2156,
    agent: {
      name: "David Rodriguez",
      phone: "+1 310 555 7890",
      email: "david@vlrealestate.com",
    },
    coordinates: { lat: 34.0259, lng: -118.7798 },
  },
  {
    id: 5,
    title: "Penthouse with City View",
    description: "A modern penthouse apartment with stunning city views.",
    location: "Tokyo, Japan",
    price: 3000000,
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 2500,
    type: "Penthouse",
    status: "For Sale",
    image: "/properties/penthouse-city-view.png",
    featured: false,
    features: ["City View", "Rooftop Terrace", "Modern Design", "High Floor"],
    amenities: ["Concierge", "Gym", "Pool", "Security"],
    highlights: ["City Views", "Penthouse Level", "Modern Design"],
    images: [
      "/properties/penthouse-city-view.png",
      "/placeholder.svg?height=300&width=400&text=City View",
      "/placeholder.svg?height=300&width=400&text=Terrace",
    ],
    yearBuilt: 2021,
    parkingSpaces: 2,
    furnished: false,
    petFriendly: false,
    pricePerSqFt: 1200,
    lastUpdated: "2024-01-14",
    viewCount: 1834,
    agent: {
      name: "Yuki Tanaka",
      phone: "+81 3 1234 5678",
      email: "yuki@vlrealestate.com",
    },
    coordinates: { lat: 35.6762, lng: 139.6503 },
  },
  {
    id: 6,
    title: "Rustic Cabin in the Woods",
    description: "A secluded cabin surrounded by nature.",
    location: "Aspen, USA",
    price: 750000,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 1000,
    type: "Cabin",
    status: "For Sale",
    image: "/properties/rustic-cabin-woods.png",
    featured: false,
    features: ["Forest Setting", "Fireplace", "Deck", "Mountain Views"],
    amenities: ["Fireplace", "Deck", "Storage", "Heating"],
    highlights: ["Forest Location", "Mountain Views", "Rustic Charm"],
    images: [
      "/properties/rustic-cabin-woods.png",
      "/placeholder.svg?height=300&width=400&text=Forest View",
      "/placeholder.svg?height=300&width=400&text=Interior",
    ],
    yearBuilt: 1995,
    parkingSpaces: 1,
    furnished: true,
    petFriendly: true,
    pricePerSqFt: 750,
    lastUpdated: "2024-01-06",
    viewCount: 423,
    agent: {
      name: "Robert Wilson",
      phone: "+1 970 555 2468",
      email: "robert@vlrealestate.com",
    },
    coordinates: { lat: 39.1911, lng: -106.8175 },
  },
  {
    id: 7,
    title: "Historic Mansion in Rome",
    description: "A grand mansion with a rich history.",
    location: "Rome, Italy",
    price: 6000000,
    bedrooms: 6,
    bathrooms: 6,
    squareFeet: 5000,
    type: "Mansion",
    status: "For Sale",
    image: "/properties/historic-mansion-rome.png",
    featured: true, // Marked as favorite
    features: ["Historic Architecture", "Large Garden", "Original Features", "City Center"],
    amenities: ["Garden", "Parking", "Security", "Storage"],
    highlights: ["Historic Property", "City Center", "Large Garden"],
    images: [
      "/properties/historic-mansion-rome.png",
      "/placeholder.svg?height=300&width=400&text=Garden",
      "/placeholder.svg?height=300&width=400&text=Interior",
    ],
    yearBuilt: 1650,
    parkingSpaces: 4,
    furnished: false,
    petFriendly: true,
    pricePerSqFt: 1200,
    lastUpdated: "2024-01-09",
    viewCount: 1567,
    agent: {
      name: "Marco Rossi",
      phone: "+39 06 1234 5678",
      email: "marco@vlrealestate.com",
    },
    coordinates: { lat: 41.9028, lng: 12.4964 },
  },
  {
    id: 8,
    title: "Seaside Villa in Greece",
    description: "A beautiful villa overlooking the Aegean Sea.",
    location: "Santorini, Greece",
    price: 2000000,
    bedrooms: 4,
    bathrooms: 4,
    squareFeet: 3500,
    type: "Villa",
    status: "For Sale",
    image: "/properties/seaside-villa-greece.png",
    featured: false,
    features: ["Sea View", "Pool", "Terrace", "Traditional Architecture"],
    amenities: ["Pool", "Terrace", "Parking", "WiFi"],
    highlights: ["Sea Views", "Traditional Style", "Pool"],
    images: [
      "/properties/seaside-villa-greece.png",
      "/placeholder.svg?height=300&width=400&text=Sea View",
      "/placeholder.svg?height=300&width=400&text=Pool",
    ],
    yearBuilt: 2010,
    parkingSpaces: 2,
    furnished: true,
    petFriendly: true,
    pricePerSqFt: 571,
    lastUpdated: "2024-01-11",
    viewCount: 987,
    agent: {
      name: "Maria Papadopoulos",
      phone: "+30 22860 12345",
      email: "maria@vlrealestate.com",
    },
    coordinates: { lat: 36.3932, lng: 25.4615 },
  },
  {
    id: 9,
    title: "Mountain Chalet in Switzerland",
    description: "A cozy chalet perfect for skiing and snowboarding.",
    location: "Zermatt, Switzerland",
    price: 1200000,
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 2200,
    type: "Chalet",
    status: "For Sale",
    image: "/properties/mountain-chalet-switzerland.png",
    featured: false,
    features: ["Mountain Views", "Fireplace", "Balcony", "Ski Access"],
    amenities: ["Fireplace", "Balcony", "Storage", "Heating"],
    highlights: ["Mountain Views", "Ski Access", "Alpine Style"],
    images: [
      "/properties/mountain-chalet-switzerland.png",
      "/placeholder.svg?height=300&width=400&text=Mountain View",
      "/placeholder.svg?height=300&width=400&text=Interior",
    ],
    yearBuilt: 2005,
    parkingSpaces: 1,
    furnished: true,
    petFriendly: false,
    pricePerSqFt: 545,
    lastUpdated: "2024-01-07",
    viewCount: 756,
    agent: {
      name: "Hans Mueller",
      phone: "+41 27 966 1234",
      email: "hans@vlrealestate.com",
    },
    coordinates: { lat: 46.0207, lng: 7.7491 },
  },
  {
    id: 10,
    title: "Desert Oasis in Dubai",
    description: "A luxurious oasis in the heart of the desert.",
    location: "Dubai, UAE",
    price: 4000000,
    bedrooms: 5,
    bathrooms: 5,
    squareFeet: 4500,
    type: "House",
    status: "For Sale",
    image: "/properties/desert-oasis-dubai.png",
    featured: false,
    features: ["Pool", "Garden", "Modern Design", "Security"],
    amenities: ["Pool", "Garden", "Security", "Parking"],
    highlights: ["Luxury Design", "Private Pool", "Modern Features"],
    images: [
      "/properties/desert-oasis-dubai.png",
      "/placeholder.svg?height=300&width=400&text=Pool Area",
      "/placeholder.svg?height=300&width=400&text=Interior",
    ],
    yearBuilt: 2022,
    parkingSpaces: 3,
    furnished: false,
    petFriendly: true,
    pricePerSqFt: 889,
    lastUpdated: "2024-01-13",
    viewCount: 1432,
    agent: {
      name: "Ahmed Al-Rashid",
      phone: "+971 50 987 6543",
      email: "ahmed@vlrealestate.com",
    },
    coordinates: { lat: 25.2048, lng: 55.2708 },
  },
  {
    id: 11,
    title: "Modern Villa",
    location: "Dubai Marina",
    price: 1900000,
    bedrooms: 3,
    bathrooms: 2,
    area: "1,200 sq ft",
    squareFeet: 1200,
    image: "/properties/modern-villa.png",
    status: "Ready",
    featured: false,
    type: "Villa",
    yearBuilt: 2022,
    parkingSpaces: 2,
    furnished: true,
    petFriendly: true,
    pricePerSqFt: 1583,
    lastUpdated: "2024-01-15",
    viewCount: 1247,
    description:
      "This stunning modern villa offers breathtaking views of Dubai Marina. With its contemporary design and premium finishes, it represents the pinnacle of luxury living in one of Dubai's most prestigious neighborhoods.",
    features: [
      "Private swimming pool",
      "Smart home technology",
      "Floor-to-ceiling windows",
      "Private garden",
      "Marble flooring",
      "Custom Italian kitchen",
      "Walk-in closets",
      "Home theater",
      "Private elevator",
    ],
    amenities: [
      "24/7 security",
      "Concierge service",
      "Fitness center",
      "Tennis court",
      "Children's playground",
      "BBQ area",
      "Residents' lounge",
      "Covered parking",
    ],
    highlights: ["Waterfront location", "Premium finishes", "Smart home ready"],
    agent: {
      name: "Sarah Johnson",
      phone: "+971 50 123 4567",
      email: "sarah@vlrealestate.com",
      image: "/agents/sarah-johnson.jpg",
    },
    nearbyPlaces: {
      schools: ["Dubai International School", "GEMS Wellington Academy"],
      hospitals: ["Dubai Hospital", "Mediclinic Dubai Mall"],
      shopping: ["Dubai Mall", "Marina Mall"],
      transport: ["Dubai Marina Metro", "Marina Walk"],
    },
    coordinates: { lat: 25.0657, lng: 55.1713 },
    videoId: "dQw4w9WgXcQ",
    images: [
      "/properties/modern-villa.png",
      "/properties/modern-villa-interior-1.png",
      "/properties/modern-villa-interior-2.png",
      "/properties/modern-villa-pool.png",
    ],
  },
  {
    id: 12,
    title: "Luxury Mansion",
    location: "Palm Jumeirah",
    price: 5200000,
    bedrooms: 4,
    bathrooms: 3,
    area: "2,400 sq ft",
    squareFeet: 2400,
    image: "/properties/luxury-mansion.png",
    status: "Ready",
    featured: false,
    type: "Mansion",
    yearBuilt: 2021,
    parkingSpaces: 4,
    furnished: false,
    petFriendly: true,
    pricePerSqFt: 2167,
    lastUpdated: "2024-01-10",
    viewCount: 892,
    description:
      "Experience unparalleled luxury in this magnificent mansion on Palm Jumeirah. With direct beach access and panoramic sea views, this property offers an exclusive lifestyle that epitomizes Dubai's reputation for opulence and grandeur.",
    features: [
      "Private beach access",
      "Infinity pool",
      "Rooftop terrace",
      "Home automation system",
      "Imported marble flooring",
      "Designer kitchen with premium appliances",
      "Walk-in wardrobes",
      "Home cinema room",
      "Wine cellar",
    ],
    amenities: [
      "24/7 security with CCTV",
      "Valet parking",
      "Private dock",
      "Beach club access",
      "Spa facilities",
      "Tennis court",
      "Landscaped gardens",
      "Multiple parking spaces",
    ],
    highlights: ["Beach access", "Private dock", "Luxury finishes"],
    agent: {
      name: "Ahmed Al-Rashid",
      phone: "+971 50 987 6543",
      email: "ahmed@vlrealestate.com",
      image: "/agents/ahmed-al-rashid.jpg",
    },
    nearbyPlaces: {
      schools: ["Regent International School", "Dubai British School"],
      hospitals: ["American Hospital Dubai", "Mediclinic Parkview"],
      shopping: ["Nakheel Mall", "Golden Mile Galleria"],
      transport: ["Palm Jumeirah Monorail", "Dubai Marina"],
    },
    coordinates: { lat: 25.1124, lng: 55.139 },
    videoId: "dQw4w9WgXcQ",
    images: [
      "/properties/luxury-mansion.png",
      "/properties/luxury-mansion-interior-1.png",
      "/properties/luxury-mansion-interior-2.png",
      "/properties/luxury-mansion-beach.png",
    ],
  },
  {
    id: 13,
    title: "Starlight Residence",
    location: "Downtown Dubai",
    price: 4500000,
    bedrooms: 2,
    bathrooms: 2,
    area: "900 sq ft",
    squareFeet: 900,
    image: "/properties/starlight-residence.png",
    status: "Off-plan",
    featured: false,
    type: "Apartment",
    yearBuilt: 2025,
    parkingSpaces: 1,
    furnished: false,
    petFriendly: false,
    pricePerSqFt: 5000,
    lastUpdated: "2024-01-20",
    viewCount: 2156,
    description:
      "Starlight Residence is a premium off-plan development in the heart of Downtown Dubai. With stunning views of the Burj Khalifa and Dubai Fountain, these exclusive apartments combine sophisticated design with an unbeatable location.",
    features: [
      "Floor-to-ceiling windows",
      "Premium finishes",
      "Smart home technology",
      "Balcony with Downtown views",
      "Custom Italian kitchen",
      "Marble bathrooms",
      "Built-in wardrobes",
      "Sound insulation",
    ],
    amenities: [
      "Infinity pool with Burj Khalifa views",
      "State-of-the-art fitness center",
      "Sky lounge",
      "Children's play area",
      "24/7 concierge",
      "Secure parking",
      "Business center",
      "Landscaped gardens",
    ],
    highlights: ["Burj Khalifa views", "Off-plan pricing", "Prime location"],
    agent: {
      name: "Maria Rodriguez",
      phone: "+971 50 456 7890",
      email: "maria@vlrealestate.com",
      image: "/agents/maria-rodriguez.jpg",
    },
    nearbyPlaces: {
      schools: ["GEMS Modern Academy", "Dubai International Academy"],
      hospitals: ["Dubai Hospital", "Mediclinic City Hospital"],
      shopping: ["Dubai Mall", "Souk Al Bahar"],
      transport: ["Burj Khalifa Metro", "Dubai Mall Metro"],
    },
    coordinates: { lat: 25.1972, lng: 55.2744 },
    videoId: "dQw4w9WgXcQ",
    images: [
      "/properties/starlight-residence.png",
      "/properties/starlight-residence-interior-1.png",
      "/properties/starlight-residence-interior-2.png",
      "/properties/starlight-residence-view.png",
    ],
  },
]

// Export the data with both names for compatibility
export { properties as propertiesData }
